# Generated by Django 2.1.1 on 2018-09-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(default='abc', max_length=120, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=1000.0, max_digits=300)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=300)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order')),
            ],
        ),
    ]
