# Generated by Django 2.1.1 on 2018-09-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180916_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
