# Generated by Django 2.1.1 on 2018-09-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20180913_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopa',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='shopb',
            old_name='price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='shopa',
            name='shopname',
        ),
        migrations.RemoveField(
            model_name='shopb',
            name='shopname',
        ),
    ]
