# Generated by Django 2.1.1 on 2018-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20180913_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopa',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopb',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
