# Generated by Django 2.1.1 on 2018-09-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='pname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Product'),
        ),
    ]
