apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: shopifyapp
  labels:
    purpose: mysqlforshop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: shopify
