# Generated by Django 2.1.1 on 2018-09-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_name'),
        ('product', '0003_auto_20180916_1748'),
        ('lineitem', '0002_auto_20180916_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together={('order', 'product')},
        ),
    ]
