# Generated by Django 2.1.1 on 2018-09-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineitem', '0003_auto_20180916_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
