---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopifyapi
  namespace: default
  labels:
    purpose: shopifyapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: shopifyapi
        image: gcr.io/shopifychallenge-216703/shopifyapi
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: shopify
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
