# Generated by Django 2.1.1 on 2018-09-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='line_items',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
